### ISSUE TITLE
Testcase failures with PHP7.0 (Ubuntu)

### ISSUE THREAD

**Issue by nacc** [twigphp/Twig#1992]
We are moving to PHP7.0 in Ubuntu 16.04 and I noticed a few testcase failures with twig.

```
PHPUnit 5.1.3 by Sebastian Bergmann and contributors.
    
    ....FF......................................................   60 / 1172 (  5%)
    ............................................................  120 / 1172 ( 10%)
    ............................................................  180 / 1172 ( 15%)
    ............................................................  240 / 1172 ( 20%)
    ............................................................  300 / 1172 ( 25%)
    ................................................
    Program received signal SIGSEGV, Segmentation fault.
    __memcpy_avx_unaligned ()
        at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:273
    273 ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S: No such file
    or directory.
    (gdb) bt
     #0  __memcpy_avx_unaligned ()
        at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:273
     #1  0x00000000004ad578 in memcpy (__len=18446744073709551614,
        __src=0x7ffff14500bc, __dest=0x7ffff179c390)
        at /usr/include/x86_64-linux-gnu/bits/string3.h:53
     #2  zend_string_init (persistent=0, len=18446744073709551614,
        str=0x7ffff14500bc "\303\237\343\201\224a")
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_string.h:159
     #3  php_pcre_split_impl (pce=pce@entry=0x11055f0,
        subject=0x7ffff14500b8 "\303\251\303\204\303\237\343\201\224a",
        subject_len=10, return_value=return_value@entry=0x7ffff361b240,
        limit_val=-1, flags=<optimized out>)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/ext/pcre/php_pcre.c:1808
     #4  0x00000000004ade8b in zif_preg_split (execute_data=<optimized out>,
        return_value=0x7ffff361b240)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/ext/pcre/php_pcre.c:1721
     #5  0x0000000000706f2a in dtrace_execute_internal (
        execute_data=<optimized out>, return_value=<optimized out>)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_dtrace.c:107
     #6  0x000000000079af90 in ZEND_DO_FCALL_SPEC_HANDLER ()
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:844
     #7  0x000000000075687b in execute_ex (ex=ex@entry=0x7ffff361b070)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:414
     #8  0x0000000000706dc1 in dtrace_execute_ex
    (execute_data=0x7ffff361b070)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_dtrace.c:83
     #9  0x000000000079b0cd in ZEND_DO_FCALL_SPEC_HANDLER ()
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:800
     #10 0x000000000075687b in execute_ex (ex=ex@entry=0x7ffff3619ff0)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:414
     #11 0x0000000000706dc1 in dtrace_execute_ex
    (execute_data=0x7ffff3619ff0)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_dtrace.c:83
     #12 0x000000000079b0cd in ZEND_DO_FCALL_SPEC_HANDLER ()
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:800
     #13 0x000000000075687b in execute_ex (ex=ex@entry=0x7ffff3619e80)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:414
     #14 0x0000000000706dc1 in dtrace_execute_ex
    (execute_data=0x7ffff3619e80)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_dtrace.c:83
     #15 0x000000000079b0cd in ZEND_DO_FCALL_SPEC_HANDLER ()
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:800
     #16 0x000000000075687b in execute_ex (ex=ex@entry=0x7ffff3619db0)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:414
     #17 0x0000000000706dc1 in dtrace_execute_ex
    (execute_data=0x7ffff3619db0)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_dtrace.c:83
     #18 0x000000000079b0cd in ZEND_DO_FCALL_SPEC_HANDLER ()
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:800
     #19 0x000000000075687b in execute_ex (ex=ex@entry=0x7ffff3619ca0)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:414
     #20 0x0000000000706dc1 in dtrace_execute_ex
    (execute_data=0x7ffff3619ca0)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_dtrace.c:83
     #21 0x000000000079b0cd in ZEND_DO_FCALL_SPEC_HANDLER ()
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:800
     #22 0x000000000075687b in execute_ex (ex=ex@entry=0x7ffff36192e0)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:414
     #23 0x0000000000706dc1 in dtrace_execute_ex
    (execute_data=0x7ffff36192e0)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_dtrace.c:83
     #24 0x000000000079b0cd in ZEND_DO_FCALL_SPEC_HANDLER ()
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:800
     #25 0x000000000075687b in execute_ex (ex=ex@entry=0x7ffff3619210)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:414
     #26 0x0000000000706dc1 in dtrace_execute_ex
    (execute_data=0x7ffff3619210)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_dtrace.c:83
     #27 0x00000000007089dc in zend_call_function
    (fci=fci@entry=0x7fffffff9ae0,
        fci_cache=fci_cache@entry=0x7fffffff9ab0)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_execute_API.c:860
     #28 0x0000000000592a42 in zim_reflection_method_invokeArgs (
        execute_data=<optimized out>, return_value=0x7ffff3618e60)
        at
    /build/php7.0-JvcPYe/php7.0-7.0.3/ext/reflection/php_reflection.c:3348
     #29 0x0000000000706f2a in dtrace_execute_internal (
        execute_data=<optimized out>, return_value=<optimized out>)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_dtrace.c:107
     #30 0x000000000079af90 in ZEND_DO_FCALL_SPEC_HANDLER ()
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:844
     #31 0x000000000075687b in execute_ex (ex=ex@entry=0x7ffff3618c60)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:414
     #32 0x0000000000706dc1 in dtrace_execute_ex
    (execute_data=0x7ffff3618c60)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_dtrace.c:83
     #33 0x000000000079b0cd in ZEND_DO_FCALL_SPEC_HANDLER ()
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:800
     #34 0x000000000075687b in execute_ex (ex=ex@entry=0x7ffff3618470)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:414
     #35 0x0000000000706dc1 in dtrace_execute_ex
    (execute_data=0x7ffff3618470)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_dtrace.c:83
     #36 0x000000000079b0cd in ZEND_DO_FCALL_SPEC_HANDLER ()
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:800
     #37 0x000000000075687b in execute_ex (ex=ex@entry=0x7ffff3617880)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:414
     #38 0x0000000000706dc1 in dtrace_execute_ex
    (execute_data=0x7ffff3617880)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_dtrace.c:83
     #39 0x000000000079b0cd in ZEND_DO_FCALL_SPEC_HANDLER ()
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:800
     #40 0x000000000075687b in execute_ex (ex=ex@entry=0x7ffff3616e20)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:414
     #41 0x0000000000706dc1 in dtrace_execute_ex
    (execute_data=0x7ffff3616e20)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_dtrace.c:83
     #42 0x000000000079b0cd in ZEND_DO_FCALL_SPEC_HANDLER ()
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:800
     #43 0x000000000075687b in execute_ex (ex=ex@entry=0x7ffff3616840)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:414
     #44 0x0000000000706dc1 in dtrace_execute_ex
    (execute_data=0x7ffff3616840)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_dtrace.c:83
     #45 0x000000000079b0cd in ZEND_DO_FCALL_SPEC_HANDLER ()
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:800
     #46 0x000000000075687b in execute_ex (ex=ex@entry=0x7ffff3616260)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:414
     #47 0x0000000000706dc1 in dtrace_execute_ex
    (execute_data=0x7ffff3616260)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_dtrace.c:83
     #48 0x000000000079b0cd in ZEND_DO_FCALL_SPEC_HANDLER ()
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:800
     #49 0x000000000075687b in execute_ex (ex=ex@entry=0x7ffff3615c80)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:414
     #50 0x0000000000706dc1 in dtrace_execute_ex
    (execute_data=0x7ffff3615c80)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_dtrace.c:83
     #51 0x000000000079b0cd in ZEND_DO_FCALL_SPEC_HANDLER ()
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:800
     #52 0x000000000075687b in execute_ex (ex=ex@entry=0x7ffff3614640)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:414
     #53 0x0000000000706dc1 in dtrace_execute_ex
    (execute_data=0x7ffff3614640)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_dtrace.c:83
     #54 0x000000000079b0cd in ZEND_DO_FCALL_SPEC_HANDLER ()
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:800
     #55 0x000000000075687b in execute_ex (ex=ex@entry=0x7ffff3614220)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:414
     #56 0x0000000000706dc1 in dtrace_execute_ex
    (execute_data=0x7ffff3614220)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_dtrace.c:83
     #57 0x000000000079b0cd in ZEND_DO_FCALL_SPEC_HANDLER ()
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:800
     #58 0x000000000075687b in execute_ex (ex=ex@entry=0x7ffff3614130)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:414
     #59 0x0000000000706dc1 in dtrace_execute_ex
    (execute_data=0x7ffff3614130)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_dtrace.c:83
     #60 0x000000000079b0cd in ZEND_DO_FCALL_SPEC_HANDLER ()
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:800
     #61 0x000000000075687b in execute_ex (ex=ex@entry=0x7ffff3614030)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:414
     #62 0x0000000000706dc1 in dtrace_execute_ex
    (execute_data=0x7ffff3614030)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_dtrace.c:83
     #63 0x00000000007a9c57 in zend_execute (
        op_array=op_array@entry=0x7ffff3683000,
        return_value=return_value@entry=0x0)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend_vm_execute.h:458
     #64 0x0000000000717053 in zend_execute_scripts (type=type@entry=8,
        retval=retval@entry=0x0, file_count=file_count@entry=3)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/Zend/zend.c:1427
     #65 0x00000000006b7a60 in php_execute_script (
        primary_file=primary_file@entry=0x7fffffffcb10)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/main/main.c:2484
     #66 0x00000000007ab924 in do_cli (argc=4, argv=0xf68130)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/sapi/cli/php_cli.c:974
     #67 0x000000000046a1b4 in main (argc=4, argv=0xf68130)
        at /build/php7.0-JvcPYe/php7.0-7.0.3/sapi/cli/php_cli.c:1345
```

**Comment by xabbuh** [comment]
A segmentation fault rather looks like an issue in the PHP version you have installed.

**Comment by nacc** [comment]
@xabbuh you are very right, I'm sorry!

**Comment by nacc** [comment]
Ok, so updating to a later version of PHP7.0 (7.0.3-7 rather than 7.0.3-5 in Debian/Ubuntu parlance), the segmentation fault is gone, but now I get:

```
1) Twig_Tests_IntegrationTest::testIntegration with data set #214 ('filters/last.test', '"last" filter', '', array('\n{{ [1, 2, 3, 4]|last }}\n{{ {...ast }}'), false, array(array('--DATA--\nreturn array('arr'
+=...4\n4\né', '\nreturn array('arr' => new Ar... 4)))\n', '', '\n4\n4\n4\n4\né')))
"last" filter (in filters/last.test)
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 '4
 4
 4
 4
-é'
+�'

/build/twig-0SRlZk/twig-1.23.1/lib/Twig/Test/IntegrationTestCase.php:219
/build/twig-0SRlZk/twig-1.23.1/lib/Twig/Test/IntegrationTestCase.php:62

2) Twig_Tests_IntegrationTest::testIntegration with data set #240 ('filters/first.test', '"first" filter', '', array('\n{{ [1, 2, 3, 4]|first }}\n{{ ...rst }}'), false, array(array('--DATA--\nreturn array('arr'
+=...1\n1\nÄ', '\nreturn array('arr' => new Ar... 4)))\n', '', '\n1\n1\n1\n1\nÄ')))
"first" filter (in filters/first.test)
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 '1
 1
 1
 1
-Ä'
+�'

/build/twig-0SRlZk/twig-1.23.1/lib/Twig/Test/IntegrationTestCase.php:219
/build/twig-0SRlZk/twig-1.23.1/lib/Twig/Test/IntegrationTestCase.php:62
```
Any hints on figuring out the underlying issue?

**Comment by stof** [comment]
@nacc do you have mbstring or no ?

**Comment by nacc** [comment]
@stof with mbstring installed, PHP 7.0 segfaults :) I've filed a bug (https://bugs.php.net/bug.php?id=71659)

**Comment by ymc-dabe** [comment]
While updating [Debian's twig packaging](https://tracker.debian.org/pkg/twig) for php7 (and upgrading to 1.24.0), I run into: https://github.com/twigphp/Twig/issues/1992#issuecomment-188380834

Installing php-mbstring solves the issue for me (without segfaults). Versions I used were:
* PHP 7.0.4-7 from Debian/sid
* mbstring ext loaded (7.0.4-7 from Debian/sid)
* phpunit 5.2.12-1 from Debian/sid
* twig 1.24.0

**Comment by Tobion** [comment]
https://bugs.php.net/bug.php?id=71659 has been fixed so I assume this issue can be closed.
