### ISSUE TITLE
Twig_Template->getParent causes Warning: Illegal offset type in isset or empty

### ISSUE THREAD

**Issue by Blixia** [twigphp/Twig#2546]
Hello,

I'm getting the following error when trying to dynamically extend with a variable as described here.
https://twig.symfony.com/doc/2.x/tags/extends.html#dynamic-inheritance

Using twig v2.4.3 and php 7.1

```
Symfony\Component\Debug\Exception\ContextErrorException: Warning: Illegal offset type in isset or empty in /home/blixia/Projects/website/vendor/twig/twig/lib/Twig/Template.php:109
Stack trace:
#0 /home/blixia/Projects/website/var/cache/twig/49/49a9fb9c57625007d7011b9e60badb81ddd5edc340680e2e84b2786e928212c5.php(23): Twig_Template->getParent(Array)
#1 /home/blixia/Projects/website/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_25da5303d8f93a0a2a9fbcf1a9dc5dc1514552efee63c83b1aa645f9da1764da->doDisplay(Array, Array)
#2 /home/blixia/Projects/website/vendor/twig/twig/lib/Twig/Template.php(366): Twig_Template->displayWithErrorHandling(Array, Array)
#3 /home/blixia/Projects/website/vendor/twig/twig/lib/Twig/Template.php(374): Twig_Template->display(Array)
#4 /home/blixia/Projects/website/vendor/twig/twig/lib/Twig/Environment.php(288): Twig_Template->render(Array)
#5 /home/blixia/Projects/website/app/routes/site.php(42): Twig_Environment->render('website/templat...', Array)
#6 [internal function]: {closure}(Object(DoctrineProxies\__CG__\Tecknicals\Entities\Content))
#7 /home/blixia/Projects/website/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Object(Closure), Array)
#8 /home/blixia/Projects/website/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#9 /home/blixia/Projects/website/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#10 /home/blixia/Projects/website/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request))
#11 /home/blixia/Projects/website/web/index.php(16): Silex\Application->run()
#12 {main}
```

I am doing the following in php
```php
$content = ['title' => 'Title'];
$layout = $twig->load('website/path/to/base/layout.html.twig');
return new Response($twig->render('website/path/to/template.html.twig', ['layout' => $layout, 'content' => $content]));
```
The layout contains the basics of a html document
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>
```
and the template the following:
```
{% extends layout %}
{% block content %}
<article>
    <h1>{{ content.title }}</h1>
</article>
{% endblock %}
```

Am I missing the obvious?
Any help is greatly appreciated!

**Comment by stof** [comment]
The `layout` variable (used in your `extends` tag) should contain the template **name**, not a Twig_TemplateWrapper instance.

**Comment by stof** [comment]
hmm, actually, the doc seems to say Twig_Template and Twig_TemplateWrapper are also supported. So there might be a bug.
@fabpot reading the code, Twig_Template seems to be supported, but not Twig_TemplateWrapper.

**Comment by madsem** [comment]
Having the exact same issue, documentation says

> If the variable evaluates to a Twig_Template or a Twig_TemplateWrapper instance, Twig will use it as the parent template:
> // {% extends layout %}
> 
> $layout = $twig->load('some_layout_template.twig');
> 
> $twig->display('template.twig', array('layout' => $layout));

Trying to do the exact same thing as @Blixia , is there a workaround known yet?
