### ISSUE TITLE
v2.8.0 - PHP error in EscaperNodeVisitor::unwrapConditional()

### ISSUE THREAD

**Issue by brandonkelly** [twigphp/Twig#2942]
As of Twig v2.8.0 I’m getting the following error:

```
TypeError: Argument 1 passed to Twig\NodeVisitor\EscaperNodeVisitor::shouldUnwrapConditional() must be an instance of Twig\Node\Expression\ConditionalExpression, instance of Twig\Node\Expression\InlinePrint given, called in /home/vagrant/dev/craft31.test/vendor/twig/twig/src/NodeVisitor/EscaperNodeVisitor.php on line 110 and defined in /home/vagrant/dev/craft31.test/vendor/twig/twig/src/NodeVisitor/EscaperNodeVisitor.php:92
Stack trace:
#0 /home/vagrant/dev/craft31.test/vendor/twig/twig/src/NodeVisitor/EscaperNodeVisitor.php(110): Twig\NodeVisitor\EscaperNodeVisitor->shouldUnwrapConditional(Object(Twig\Node\Expression\InlinePrint), Object(craft\web\twig\Environment), 'html')
#1 /home/vagrant/dev/craft31.test/vendor/twig/twig/src/NodeVisitor/EscaperNodeVisitor.php(77): Twig\NodeVisitor\EscaperNodeVisitor->unwrapConditional(Object(Twig\Node\Expression\ConditionalExpression), Object(craft\web\twig\Environment), 'html')
#2 /home/vagrant/dev/craft31.test/vendor/twig/twig/src/NodeVisitor/AbstractNodeVisitor.php(31): Twig\NodeVisitor\EscaperNodeVisitor->doLeaveNode(Object(Twig\Node\PrintNode), Object(craft\web\twig\Environment))
#3 /home/vagrant/dev/craft31.test/vendor/twig/twig/src/NodeTraverser.php(77): Twig\NodeVisitor\AbstractNodeVisitor->leaveNode(Object(Twig\Node\PrintNode), Object(craft\web\twig\Environment))
#4 /home/vagrant/dev/craft31.test/vendor/twig/twig/src/NodeTraverser.php(68): Twig\NodeTraverser->traverseForVisitor(Object(Twig\NodeVisitor\EscaperNodeVisitor), Object(Twig\Node\PrintNode))
#5 /home/vagrant/dev/craft31.test/vendor/twig/twig/src/NodeTraverser.php(68): Twig\NodeTraverser->traverseForVisitor(Object(Twig\NodeVisitor\EscaperNodeVisitor), Object(Twig\Node\Node))
#6 /home/vagrant/dev/craft31.test/vendor/twig/twig/src/NodeTraverser.php(68): Twig\NodeTraverser->traverseForVisitor(Object(Twig\NodeVisitor\EscaperNodeVisitor), Object(Twig\Node\Node))
#7 /home/vagrant/dev/craft31.test/vendor/twig/twig/src/NodeTraverser.php(68): Twig\NodeTraverser->traverseForVisitor(Object(Twig\NodeVisitor\EscaperNodeVisitor), Object(Twig\Node\IfNode))
#8 /home/vagrant/dev/craft31.test/vendor/twig/twig/src/NodeTraverser.php(68): Twig\NodeTraverser->traverseForVisitor(Object(Twig\NodeVisitor\EscaperNodeVisitor), Object(Twig\Node\Node))
#9 /home/vagrant/dev/craft31.test/vendor/twig/twig/src/NodeTraverser.php(68): Twig\NodeTraverser->traverseForVisitor(Object(Twig\NodeVisitor\EscaperNodeVisitor), Object(Twig\Node\BodyNode))
#10 /home/vagrant/dev/craft31.test/vendor/twig/twig/src/NodeTraverser.php(53): Twig\NodeTraverser->traverseForVisitor(Object(Twig\NodeVisitor\EscaperNodeVisitor), Object(Twig\Node\ModuleNode))
#11 /home/vagrant/dev/craft31.test/vendor/twig/twig/src/Parser.php(119): Twig\NodeTraverser->traverse(Object(Twig\Node\ModuleNode))
#12 /home/vagrant/dev/craft31.test/vendor/twig/twig/src/Environment.php(574): Twig\Parser->parse(Object(Twig\TokenStream))
#13 /home/vagrant/dev/craft31.test/vendor/twig/twig/src/Environment.php(606): Twig\Environment->parse(Object(Twig\TokenStream))
#14 /home/vagrant/dev/craft31/src/web/twig/Environment.php(63): Twig\Environment->compileSource(Object(Twig\Source))
#15 /home/vagrant/dev/craft31.test/vendor/twig/twig/src/Environment.php(407): craft\web\twig\Environment->compileSource(Object(Twig\Source))
#16 /home/vagrant/dev/craft31.test/vendor/twig/twig/src/Environment.php(381): Twig\Environment->loadClass('__TwigTemplate_...', '_includes/forms...', NULL)
#17 /home/vagrant/dev/craft31/src/web/twig/Environment.php(44): Twig\Environment->loadTemplate('_includes/forms...', NULL)
#18 /home/vagrant/dev/craft31.test/vendor/twig/twig/src/Template.php(324): craft\web\twig\Environment->loadTemplate('_includes/forms...', NULL)
```

Looks like maybe `$expr2` should be `$expr3` on this line:

https://github.com/twigphp/Twig/blob/26517b0e879865ee0d8a9748144be0875d838f5a/src/NodeVisitor/EscaperNodeVisitor.php#L110

**Comment by stof** [comment]
can you send a PR ?

**Comment by brandonkelly** [comment]
I’m not familiar with that part of the code so not confident enough about the fix to submit a PR.

**Comment by stof** [comment]
Well, the line to change is the one you identified. And using the right variable is indeed what should be done.

**Comment by fabpot** [comment]
@brandonkelly I'm going to make the fix and a new release.

**Comment by fabpot** [comment]
see #2943

**Comment by brandonkelly** [comment]
Thanks @fabpot!

**Comment by fabpot** [comment]
Versions 1.39.1 and 2.8.1 released.
