### ISSUE TITLE
importing macros in an imported macro file

### ISSUE THREAD

**Issue by kmirzavaziri** [twigphp/Twig#3640]
### twig_call_macro(): Argument # 1 ($template) must be of type Twig\Template, null given, called in /var/www/vendor/twig/twig/src/Environment.php(358) : eval()'d code on line *

I have some twig files like these

a.twig
```
{% extends 'eve.twig' %}
{% import 'components.twig' as components %}
{% import 'b.twig' as b %}

{% block body %}
    {{ b.some_macro() }}
{% endblock %}
```

and

b.twig
```
{% import 'components.twig' as components %}

{% macro some_macro() %}
    {{ components.div() }}
{% endmacro %}
```

components.twig
```
{% macro div() %}
    <div>just-a-test</div>
{% endmacro %}
```

eve.twig
```
<html>
    <head></head>
    <body>{% block body %}{% endblock %}</body>
</html>
```

When I render `a.twig`, I expect everything to work fine but I receive the following error:

```
TypeError occurred on /var/www/vendor/twig/twig/src/Extension/CoreExtension.php:1187:

twig_call_macro(): Argument #1 ($template) must be of type Twig\Template, null given, called in /var/www/vendor/twig/twig/src/Environment.php(358) : eval()'d code on line 57

Trace:
#0 /var/www/vendor/twig/twig/src/Environment.php(358) : eval()'d code(57): twig_call_macro()
#1 /var/www/vendor/twig/twig/src/Extension/CoreExtension.php(1200): __TwigTemplate_34a2c8b4259fded11e1f1661f9f36bfa->macro_main()
#2 /var/www/vendor/twig/twig/src/Environment.php(358) : eval()'d code(105): twig_call_macro()
#3 /var/www/vendor/twig/twig/src/Template.php(171): __TwigTemplate_e95d97cda9e88725c651fc4f14c12206->block_body()
#4 /var/www/vendor/twig/twig/src/Environment.php(358) : eval()'d code(312): Twig\Template->displayBlock()
#5 /var/www/vendor/twig/twig/src/Template.php(171): __TwigTemplate_5b0de99bc2b4432aaa87c0a845c31a90->block_full_body()
#6 /var/www/vendor/twig/twig/src/Environment.php(358) : eval()'d code(90): Twig\Template->displayBlock()
#7 /var/www/vendor/twig/twig/src/Template.php(394): __TwigTemplate_5b0de99bc2b4432aaa87c0a845c31a90->doDisplay()
#8 /var/www/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#9 /var/www/vendor/twig/twig/src/Environment.php(358) : eval()'d code(51): Twig\Template->display()
#10 /var/www/vendor/twig/twig/src/Template.php(394): __TwigTemplate_e95d97cda9e88725c651fc4f14c12206->doDisplay()
#11 /var/www/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#12 /var/www/vendor/twig/twig/src/Template.php(379): Twig\Template->display()
#13 /var/www/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render()
#14 /var/www/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render()
#15 /var/www/vendor/xua/core/src/Services/TemplateService.php(29): Twig\Environment->render()
#16 /var/www/src/Services/RenderService.php(111): Xua\Core\Services\TemplateService::render()
#17 /var/www/src/Services/VarqueInterface.php(89): Avistopia\Shared\Services\RenderService::render()
#18 /var/www/src/Interfaces/Course/Home.php(25): Avistopia\Shared\Services\VarqueInterface::interfaceExecution()
#19 /var/www/vendor/xua/core/src/Services/RouteService.php(68): Avistopia\Shared\Interfaces\Course\Home::execute()
#20 /var/www/vendor/xua/core/src/Services/MainService.php(36): Xua\Core\Services\RouteService::execute()
#21 /var/www/main.php(6): Xua\Core\Services\MainService::main()
#22 {main}
```

Which I think is because the `$macros['components']` is not defined when evaluating the compiled code of `b.twig` (the method `macro_some_macro` on the class that is compiled from `b.twig` template) since the doDisplay method is not called somehow.

**Comment by stof** [comment]
macros have their own scope for their body, isolated from the template scope. So you should put your import inside the macro body.
